[workspace]
authors = ["Akulen <tomas@rigaux.com>"]
channels = ["conda-forge"]
name = "AlphaGateau"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
[tasks.train]
    cmd = "python train.py"
    [tasks.train.env]
    XLA_PYTHON_CLIENT_ALLOCATOR = "platform"
[tasks.rank]
    cmd = "python ranking.py"
    [tasks.rank.env]
    XLA_PYTHON_CLIENT_ALLOCATOR = "platform"
[tasks.book]
    cmd = "python book.py"

[system-requirements]
cuda = "12.0"

[dependencies]
python = "==3.11.9"
aim = ">=3.27.0,<4"
optax = ">=0.2.6,<0.3"
flax = ">=0.10.4,<0.11"
jraph = ">=0.0.6.dev0,<0.0.7"
jax = "<0.6"
chex = ">=0.1.90,<0.2"
scikit-learn = ">=1.8.0,<2"
statsmodels = ">=0.14.6,<0.15"

[pypi-dependencies]
humanhash3 = ">=0.0.6, <0.0.7"
pgx = "<2.4"
mctx = ">=0.0.5, <0.0.6"
